openapi: 3.0.0
info:
  title: CatalogShop API
  description: API documentation for CatalogShop management
  version: "1.0.0"
tags:
  - name: "Catalog Shop"
    description: "API related to Catalog Shop management"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /catalogShop/:
    post:
      tags:
        - "Catalog Shop"
      summary: "Create a new Catalog Shop"
      description: "Create a new catalog for the shop."
      operationId: "newCatalogShop"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                catalog_name:
                  type: string
                  description: "Name of the catalog"
                catalog_description:
                  type: string
                  description: "Description of the catalog"
      responses:
        200:
          description: "Catalog created successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      catalogId:
                        type: string
        400:
          description: "Bad request"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
      security:
        - bearerAuth: []

  /catalogShop/{shopId}:
    get:
      tags:
        - "Catalog Shop"
      summary: "Get all Catalog Shops of a specific shop"
      description: "Retrieve all catalog shops for a given shop ID."
      operationId: "getCatalogShop"
      parameters:
        - name: "shopId"
          in: "path"
          required: true
          description: "ID of the shop"
          schema:
            type: string
      responses:
        200:
          description: "A list of catalog shops"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    catalog_name:
                      type: string
                    catalog_description:
                      type: string
        404:
          description: "Shop not found"
        400:
          description: "Invalid shop ID"
      security:
        - bearerAuth: []

security:
  - bearerAuth: []
