openapi: 3.0.0
info:
  title: Access API
  version: 1.0.0
  description: API endpoints liên quan đến các thao tác người dùng như đăng ký, đăng nhập, đăng xuất, và cấp mới token.
tags:
  - name: Access
    description: API endpoints liên quan đến các thao tác người dùng.

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /signup:
    post:
      tags:
        - Access
      summary: Đăng ký người dùng mới
      description: API này đăng ký một người dùng mới.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "a41954@gmail.com"
                password:
                  type: string
                  example: "12345678"
      responses:
        201:
          description: User registered successfully
        400:
          description: Bad request

  /signin:
    post:
      tags:
        - Access
      summary: Đăng nhập người dùng
      description: API này đăng nhập một người dùng đã tồn tại.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "a41954@gmail.com"
                password:
                  type: string
                  example: "12345678"
      responses:
        200:
          description: User signed in successfully
        401:
          description: Unauthorized

  /logout:
    post:
      tags:
        - Access
      summary: Đăng xuất người dùng
      description: API này đăng xuất người dùng bằng cách vô hiệu hóa access token hiện tại.
      security:
        - bearerAuth: []
      responses:
        200:
          description: Đăng xuất thành công
        401:
          description: Unauthorized - Token không hợp lệ hoặc đã hết hạn
        500:
          description: Lỗi server

  /refresh-token:
    post:
      tags:
        - Access
      summary: Cấp mới access token
      description: API này cấp một access token mới bằng cách sử dụng refresh token hiện có trong body của yêu cầu.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
                  description: Refresh token hiện tại.
                  example: "sampleRefreshToken123"
      responses:
        200:
          description: Cấp mới access token thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: Access token mới được cấp.
        400:
          description: Bad Request - Access token không được cung cấp hoặc không hợp lệ
        401:
          description: Unauthorized - Refresh token không hợp lệ hoặc đã hết hạn
        500:
          description: Lỗi server
  /fotgot-password:
    post:
      tags:
        - Access
      summary: Đừa sửa mật khách hãng
      description: API này đừa sửa mật khách hãng bằng cách sử dụng email hiện tại.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "a41954@gmail.com"
      responses:
        200:
          description: Đừa sửa mật khách hãng thành công
        400:
          description: Bad request - Email hãng không hoặc trảng thái kết nối