openapi: 3.0.0
info:
  title: API Documentation
  description: API endpoints liên quan đến thao tác đặt hàng và các chức năng khác
  version: 1.0.0
servers:
  - url: http://localhost:8080/api

tags:
  - name: Orders
    description: API endpoints liên quan đến các thao tác với đơn hàng.
  - name: Category
    description: API endpoints liên quan đến các thao tác với danh mục.

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []  # Sử dụng JWT Authentication cho tất cả các endpoints

paths:
  /order:
    post:
      summary: Tạo đơn hàng mới
      description: API này tạo một hoặc nhiều đơn hàng cho người dùng. Mỗi đơn hàng có thể chứa nhiều sản phẩm.Nếu chọn thanh toán online thì redirect đến link thanh toán
      tags:
        - Orders
      security:
        - bearerAuth: []  # Chỉ định JWT bảo mật cho endpoint này
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                orders:
                  type: array
                  description: Danh sách các đơn hàng
                  items:
                    type: object
                    properties:
                      shopId:
                        type: string
                        description: ID của cửa hàng
                        example: 60a6c6d8f1e1c300b0fcb6e9
                      products:
                        type: array
                        description: Danh sách sản phẩm trong đơn hàng
                        items:
                          type: object
                          properties:
                            productId:
                              type: string
                              description: ID của sản phẩm
                              example: 60a6c6d8f1e1c300b0fcb6e8
                            quantity:
                              type: integer
                              description: Số lượng sản phẩm
                              example: 1
                            price:
                              type: integer
                              description: Giá của sản phẩm (VND)
                              example: 2500
                            product_name:
                              type: string
                              description: Tên sản phẩm
                              example: "Sản phẩm A"
                            product_thumb:
                              type: string
                              description: URL ảnh của sản phẩm
                              example: "url_ảnh_sản_phẩm_A"
                      totalPrice:
                        type: integer
                        description: Tổng giá trị của đơn hàng (VND)
                        example: 3500
                paymentMethod:
                  type: string
                  description: Phương thức thanh toán
                  example: "online"
                  enum: [cash, online]
                paymentGateway:
                  type: string
                  description: Cổng thanh toán sử dụng cho phương thức online
                  example: "VNPAY"
                shippingAddress:
                  type: string
                  description: Địa chỉ giao hàng
                  example: "456 Đường XYZ, Quận 1, TP.HCM"
      responses:
        '200':
          description: Thành công - trả về danh sách đơn hàng đã tạo và tổng giá trị đơn hàng
          content:
            application/json:
              schema:
                type: object
                properties:
                  orders:
                    type: array
                    description: Danh sách các đơn hàng đã tạo
                    items:
                      type: object
                      properties:
                        order_userId:
                          type: string
                          description: ID của người dùng
                          example: 60a6c6d8f1e1c300b0fcb6d9
                        order_trackingNumber:
                          type: string
                          description: Mã tracking của đơn hàng
                          example: "t3g1624876405000"
                        order_shopId:
                          type: string
                          description: ID của cửa hàng
                          example: 60a6c6d8f1e1c300b0fcb6e9
                        order_products:
                          type: array
                          description: Danh sách sản phẩm trong đơn hàng
                          items:
                            type: object
                            properties:
                              productId:
                                type: string
                                description: ID của sản phẩm
                                example: 60a6c6d8f1e1c300b0fcb6e8
                              quantity:
                                type: integer
                                description: Số lượng sản phẩm
                                example: 1
                              price:
                                type: integer
                                description: Giá sản phẩm (VND)
                                example: 2500
                              product_name:
                                type: string
                                description: Tên sản phẩm
                                example: "Sản phẩm A"
                              product_thumb:
                                type: string
                                description: URL ảnh sản phẩm
                                example: "url_ảnh_sản_phẩm_A"
                        order_total_price:
                          type: integer
                          description: Tổng giá trị đơn hàng (VND)
                          example: 3500
                        order_payment_method:
                          type: string
                          description: Phương thức thanh toán
                          example: "online"
                        order_payment_gateway:
                          type: string
                          description: Cổng thanh toán
                          example: "VNPAY"
                        order_shipping_address:
                          type: string
                          description: Địa chỉ giao hàng
                          example: "456 Đường XYZ, Quận 1, TP.HCM"
                        order_status:
                          type: string
                          description: Trạng thái đơn hàng
                          example: "pending"
                  totalAmountOrders:
                    type: integer
                    description: Tổng giá trị của tất cả các đơn hàng (VND)
                    example: 38500
        '400':
          description: Lỗi yêu cầu không hợp lệ
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Thông báo lỗi
                    example: "User id is required"

  
  /order/{id}:
    get:
      summary: Lọc đơn hang
      description: Lọc đơn hang theo ID
      tags:
        - Orders
      security:
        - bearerAuth: []  # Chỉ định JWT bảo mật cho endpoint không
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Thành cảc
          content:
            application/json:
              schema:
                type: object
                properties:
                  order:
                    type: object
                    properties:
                      order_userId:
                        type: string
                        description: ID của người dùng
                        example: 60a6c6d8f1e1c300b0fcb6d9
                      order_trackingNumber:
                        type: string
                        description: Mã tracking của đơn hang
                        example: "t3g1624876405000"
                      order_shopId:
                        type: string
                        description: ID của cửa hàng
                        example: 60a6c6d8f1e1c300b0fcb6e9
                      order_products:
                        type: array
                        description: Danh sách san pham trong don hang
                        items:
                          type: object
                          properties:
                            productId:
                              type: string
                              description: ID san pham
                              example: 60a6c6d8f1e1c300b0fcb6e8
                            quantity:
                              type: integer
                              description: So luong san pham
                              example: 1
                            price:
                              type: integer
                              description: Gia san pham
                              example: 2500
                            product_name:
                              type: string
                              description: Ten san pham
                              example: "San pham A"
    # put:
    #   summary: Chinh sua don hang
    #   description: Chinh sua don hang theo ID
    #   tags:
    #     - Orders
    #   security:
    #     - bearerAuth: []  # Chỉ định JWT bảo mật cho endpoint không
    #   parameters:
    #     - in: path
    #       name: id
    #       required: true
    #       schema:
    #         type: string
    #   requestBody:
    #     required: true
    #     content:
    #       application/json:
    #         schema:
    #           type: object
    #           properties:
    #             order_userId:
    #               type: string
    #               description: ID user
    #               example: 60a6c6d8f1e1c300b0fcb6d9
    #             order_trackingNumber:
    #               type: string
    #               description: Mã tracking
    #               example: "t3g1624876405000"
    #             order_shopId:
    #               type: string
    #               description: ID cửa
    #               example: 60a6c6d8f1e1c300b0fcb6e9
    #             order_products:
    #               type: array
    #               description: Danh sách san pham trong don hang
    #               items:
    #                 type: object
    #                 properties:
  
  /order/user:
    get:
      summary: list đơn hàng của user
      description: list đơn hang theo userId
      tags:
        - Orders
      security:
        - bearerAuth: []  # Chỉ định JWT bảo mật cho endpoint không
      parameters:
        - in: query
          name: status
          schema:
            type: string
          description: status
      responses:
        '200':
          description: các đơn hàng của user
          content:
            application/json:
              schema:
                type: object
                properties:
                  orders:
                    type: array
                    description: Danh sách đơn hang của user
                    items:
                      type: object
                      properties:
                        order_userId:
                          type: string
                          description: ID user
                          example: 60a6c6d8f1e1c300b0fcb6d9
 