openapi: 3.0.0
info:
  title: Cart API
  version: 1.0.0
  description: API endpoints liên quan đến các thao tác với giỏ hàng như tạo, cập nhật, xóa nhiều sản phẩm.

tags:
  - name: Cart
    description: API endpoints liên quan đến các thao tác với giỏ hàng.

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /cart:
    get:
      tags:
        - Cart
      summary: Lấy danh sách sản phẩm trong giỏ hàng
      description: API này cho phép người dùng xem sản phẩm trong giỏ hàng.
      security:
        - bearerAuth: []
      responses:
        200:
          description: Danh sách sản phẩm trong giỏ hàng
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      type: object
                      properties:
                        productId:
                          type: string
                        quantity:
                          type: integer
                        price:
                          type: number
                        name:
                          type: string
                  total:
                    type: number
        401:
          description: Unauthorized
        500:
          description: Internal Server Error

    post:
      tags:
        - Cart
      summary: Thêm sản phẩm vào giỏ hàng
      description: API này cho phép người dùng thêm sản phẩm vào giỏ hàng.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
                  example: "66bb25b1c20ba387f1a4705d"
                quantity:
                  type: integer
                  example: 1
      responses:
        201:
          description: Sản phẩm đã được thêm vào giỏ hàng
        400:
          description: Bad request
        401:
          description: Unauthorized

  /cart/{productId}:  
    delete:
      tags:
        - Cart
      summary: Xóa sản phẩm khỏi giỏ hàng dựa trên ID
      description: API này xóa một sản phẩm dựa trên ID.
      parameters:
        - in: path
          name: productId
          description: ID của sản phẩm cần xóa
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        204:
          description: Sản phẩm đã được xóa khỏi giỏ hàng
        404:
          description: Sản phẩm không tìm thấy
        401:
          description: Unauthorized

  /cart/products/quantity:
    post:
      tags:
        - Cart
      summary: Cập nhật số lượng sản phẩm trong giỏ hàng
      description: API này cho phép người dùng cập nhật số lượng sản phẩm trong giỏ hàng.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
                  example: "66bb25b1c20ba387f1a4705d"
                quantity:
                  type: integer
                  example: 1
                old_quantity:
                  type: integer
                  example: 2
      responses:
        200:
          description: Số lượng đã được cập nhật trong giỏ hàng
        404:
          description: Không tìm thấy sản phẩm
        400:
          description: Bad request
        401:
          description: Unauthorized

  /cart/products:
    delete:
      tags:
        - Cart
      summary: Xóa nhiều sản phẩm trong giỏ hàng theo mảng ID
      description: API này cho phép người dùng xóa các sản phẩm trong giỏ hàng.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productIds:
                  type: array
                  items:
                    type: string
                  example: ["66bb25b1c20ba387f1a4705d"]
      responses:
        204:
          description: Các sản phẩm đã được xóa khỏi giỏ hàng
        404:
          description: Không tìm thấy sản phẩm
        401:
          description: Unauthorized
